
import Footer from "@/Components/Footer";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Inter } from 'next/font/google'; 




const inter = Inter({
  subsets: ['latin'], 
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        
        {children}
        <Footer/>
        </body>
    </html>
  );
}
